trigger:
- '*'

pool:
  name: Default
  demands: LabVIEW

steps:
- task: CmdLine@2
  displayName: 'Restore packages'
  inputs:
    script: 'LabVIEWCLI -LabVIEWPath "%LabVIEW%\LabVIEW.exe" -AdditionalOperationDirectory "$(Build.SourcesDirectory)\Toolchain" -OperationName Restore -Configuration "$(Build.SourcesDirectory)\LVUnit.vipc"'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@2
  displayName: 'Run tests'
  inputs:
    script: 'LabVIEWCLI -LabVIEWPath "%LabVIEW%\LabVIEW.exe" -AdditionalOperationDirectory "$(Build.SourcesDirectory)\Toolchain" -OperationName Test -Project "$(Build.SourcesDirectory)\LVUnit.lvproj" -ResultsFolder "$(System.DefaultWorkingDirectory)\TestResults"'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '**/COVERAGE-*.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/src'
    failIfCoverageEmpty: true
